name: solvix
description: "Solvix Messanger."
publish_to: 'none'
version: 1.0.1+1


environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  http: ^1.4.0
  signalr_core: ^1.1.2
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8
  pinput: ^5.0.1
  font_awesome_flutter: ^10.8.0
  logging: ^1.3.0
  intl: ^0.20.2
  rxdart: ^0.28.0
  uuid: ^4.5.1
  timezone: ^0.10.1
  shamsi_date: ^1.1.0
  flutter_timezone: ^4.1.1
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  fluttertoast: ^8.2.12
  permission_handler: ^12.0.0+1
  flutter_contacts: ^1.1.9+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  connectivity_plus: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

dependency_overrides:
  web_socket_channel: ^3.0.3
  web: ^1.1.1



flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"

  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/